# Generated by Django 3.2.11 on 2022-01-11 23:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('photo', models.URLField(max_length=400, validators=[django.core.validators.URLValidator])),
                ('special_price', models.FloatField(blank=True, null=True)),
                ('strat_hour', models.DateTimeField(blank=True, null=True)),
                ('end_hour', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=False, null=True)),
                ('special', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('strat_hour', models.DateTimeField(null=True)),
                ('end_hour', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_vip', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='item_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_menu.item')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items_menu.menu')),
            ],
        ),
    ]
