# Generated by Django 3.2.11 on 2022-01-09 23:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('photo', models.URLField(max_length=400, validators=[django.core.validators.URLValidator])),
                ('special_price', models.FloatField(blank=True, null=True)),
                ('strat_hour', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(regex='^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$')])),
                ('end_hour', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(regex='^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$')])),
                ('available', models.BooleanField(default=False, null=True)),
                ('special', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('strat_hour', models.DateTimeField(null=True)),
                ('end_hour', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='item_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.item')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menu')),
            ],
        ),
    ]
