# Generated by Django 3.2.11 on 2022-01-10 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='end_hour',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(regex='^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='strat_hour',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(regex='^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$')]),
        ),
    ]
