# Generated by Django 3.2.11 on 2022-01-11 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_auto_20220111_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.URLField(blank=True, max_length=400, null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
