# Generated by Django 3.2.11 on 2022-01-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_auto_20220111_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='loc',
            field=models.CharField(choices=[('out-side', 'out-side'), ('in-side', 'in-side')], max_length=20, null=True),
        ),
    ]
