# Generated by Django 3.2.11 on 2022-01-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0007_auto_20220112_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('coffee', 'coffee'), ('dish', 'dish'), ('full-meal', 'full-meal'), ('breakfast', 'breakfast'), ('dinner', 'dinner'), ('lunch', 'lunch'), ('alcohol', 'alcohol')], default='dish', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
