# Generated by Django 3.2.11 on 2022-01-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0008_auto_20220112_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='order_item',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('coffee', 'coffee'), ('dish', 'dish'), ('full-meal', 'full-meal'), ('breakfast', 'breakfast'), ('dinner', 'dinner'), ('lunch', 'lunch'), ('alcohol', 'alcohol'), ('beverage', 'beverage')], max_length=20),
        ),
    ]
