# Generated by Django 3.2.11 on 2022-01-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0009_auto_20220116_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='table_loc',
            field=models.CharField(choices=[('out-side', 'out-side'), ('in-side', 'in-side')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('coffee', 'coffee'), ('dish', 'dish'), ('full-meal', 'full-meal'), ('breakfast', 'breakfast'), ('dinner', 'dinner'), ('lunch', 'lunch'), ('alcohol', 'alcohol'), ('beverage', 'beverage'), ('business', 'business')], max_length=20),
        ),
    ]
