# Generated by Django 3.2.11 on 2022-01-20 23:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0010_auto_20220120_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('credit_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('expiry_date', models.DateTimeField()),
                ('ccv', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.order')),
            ],
        ),
    ]
