# Generated by Django 3.2.11 on 2022-01-22 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0013_payment_credit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='credit_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
